### ISSUE TITLE
I found CVE problems.

### ISSUE THREAD

**Issue by longJ91** [Samsung/TizenRT#942]
Hello I used the IoTcube(security vulnerabilities analysis program) to TizenRT open source code.
So, I found that three CVE problems.
i.e CVE-2015-5314, CVE-2015-5315, CVE-2015-5316

CVE-2015-5314 problem in eap_server_pwd.c
line are 852~ and 869~
CVE-2015-5315 and CVE-2015-5316 problems in  eap_pwd.c
line are 671~ , 787~ and 810~

**Comment by sunghan-chang** [comment]
@longJ91 I am so sorry for delay response.
Those files which you mentioned are not used in TizenRT, not compiled. And wpa_supplicant was come from another opensource project. That's why we don't want to fix or remove them. Instead of removing, we make a new config to notice that it has CVE issues and we don't recommand to use. As you know, TizenRT is an opensource project as well. Even though it has CVE problems, user can enable eap functionality and use it. That is a user choice.
Anyway you can refer our new config in #1235 .
If you have additional query, please let us know. If you don't, let's close this.
